# CONFIG_SERIAL=y
# CONFIG_NATIVE_UART_0_ON_STDINOUT=y
# CONFIG_PRINTK=y
# CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_SHELL=y
CONFIG_SHELL_PROMPT_UART="ecfw:~$ "
# CONFIG_LOG=y


# +- COREDUMP
# CONFIG_DEBUG_COREDUMP=y
# CONFIG_DEBUG_COREDUMP_BACKEND_LOGGING=y
# CONFIG_FLASH=y
# CONFIG_DEBUG_COREDUMP_BACKEND_FLASH_PARTITION=y
# CONFIG_DEBUG_COREDUMP_MEMORY_DUMP_MIN=y 