west:
  url: https://github.com/zephyrproject-rtos/west
  version: v0.7.2

manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos 
    - name: zephyrproject_nuvoton
      url-base: https://github.com/Nuvoton-EC-FAE/

  projects:
    - name: zephyr
      path: zephyr
      remote: zephyrproject_nuvoton
      revision: npcx-v3.5.0
      clone-depth: 1
      west-commands: scripts/west-commands.yml

    - name: cmsis
      remote: zephyrproject
      revision: 5a00331455dd74e31e80efa383a489faea0590e3
      path: modules/hal/cmsis
      groups:
        - hal
    - name: mcuboot
      remote: zephyrproject
      revision: 13767d0b72eb14ce42eb8aad1e5a133ef66afc54
      path: bootloader/mcuboot
  self:
    path: ecfw_demo