# 現有配置
CONFIG_SHELL=y
CONFIG_LOG=y
CONFIG_EC_LOG_LEVEL=4
CONFIG_DEBUG_THREAD_INFO=y

# 調試配置
# CONFIG_DEBUG=y
# CONFIG_DEBUG_INFO=y
CONFIG_DEBUG_COREDUMP=y
CONFIG_DEBUG_COREDUMP_BACKEND_LOGGING=y
CONFIG_DEBUG_COREDUMP_MEMORY_DUMP_MIN=y

